project_id = "arqugyvmegxonaerjbzd"

[functions.match-jobs]
verify_jwt = true

[functions.test-llm-chat]
verify_jwt = false

[functions.generate-application]
verify_jwt = false

[functions.ingest-jobs]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
