-- Sample jobs for testing the JobMatch platform
-- Run this in Supabase SQL Editor to populate the database with test data

INSERT INTO jobs (
  title, 
  company, 
  description, 
  location, 
  salary_min, 
  salary_max, 
  salary_currency,
  is_remote, 
  employment_type, 
  required_skills, 
  experience_level, 
  url, 
  posted_at,
  is_active
)
VALUES 
  (
    'Senior React Developer',
    'TechCorp',
    'We are looking for an experienced React developer to join our growing team. You will work on building scalable web applications using modern technologies. Must have strong experience with React, TypeScript, and state management.',
    'San Francisco, CA',
    120000, 
    180000,
    'USD',
    true,
    'full-time',
    ARRAY['React', 'TypeScript', 'Node.js', 'Redux', 'GraphQL'],
    'senior',
    'https://example.com/jobs/react-dev',
    NOW(),
    true
  ),
  (
    'Frontend Engineer',
    'StartupXYZ',
    'Join our fast-growing startup as a frontend engineer. Build beautiful user interfaces and work directly with designers and product managers. Experience with Vue.js is a plus.',
    'Remote',
    90000, 
    130000,
    'USD',
    true,
    'full-time',
    ARRAY['Vue.js', 'JavaScript', 'CSS', 'Tailwind', 'Figma'],
    'mid',
    'https://example.com/jobs/frontend-eng',
    NOW(),
    true
  ),
  (
    'Full Stack Developer',
    'BigCo',
    'Build scalable applications for millions of users. Work with Python, Django, and React. Must have experience with both frontend and backend development.',
    'New York, NY',
    100000, 
    150000,
    'USD',
    false,
    'full-time',
    ARRAY['Python', 'Django', 'React', 'PostgreSQL', 'AWS'],
    'mid',
    'https://example.com/jobs/fullstack',
    NOW(),
    true
  ),
  (
    'Junior Web Developer',
    'WebAgency',
    'Great opportunity for a junior developer to learn and grow. Work on client projects using modern web technologies. Mentorship provided.',
    'Austin, TX',
    60000, 
    80000,
    'USD',
    false,
    'full-time',
    ARRAY['HTML', 'CSS', 'JavaScript', 'WordPress'],
    'junior',
    'https://example.com/jobs/junior-web',
    NOW(),
    true
  ),
  (
    'DevOps Engineer',
    'CloudTech',
    'Manage and scale our cloud infrastructure. Experience with Kubernetes, Docker, and CI/CD pipelines required. Work with a talented team of engineers.',
    'Remote',
    110000, 
    160000,
    'USD',
    true,
    'full-time',
    ARRAY['Kubernetes', 'Docker', 'AWS', 'Terraform', 'CI/CD'],
    'senior',
    'https://example.com/jobs/devops',
    NOW(),
    true
  ),
  (
    'Mobile Developer (React Native)',
    'MobileFirst',
    'Build cross-platform mobile applications using React Native. Work on both iOS and Android apps. Experience with native modules is a plus.',
    'Los Angeles, CA',
    95000, 
    140000,
    'USD',
    true,
    'full-time',
    ARRAY['React Native', 'JavaScript', 'iOS', 'Android', 'Redux'],
    'mid',
    'https://example.com/jobs/mobile-dev',
    NOW(),
    true
  ),
  (
    'Backend Engineer (Node.js)',
    'APICompany',
    'Design and build RESTful APIs and microservices. Strong Node.js and database experience required. Work on high-traffic systems.',
    'Seattle, WA',
    105000, 
    155000,
    'USD',
    false,
    'full-time',
    ARRAY['Node.js', 'Express', 'MongoDB', 'Redis', 'Microservices'],
    'mid',
    'https://example.com/jobs/backend-node',
    NOW(),
    true
  ),
  (
    'UI/UX Designer & Developer',
    'DesignStudio',
    'Unique role combining design and development. Create beautiful designs and implement them in code. Must have strong design sense and frontend skills.',
    'Remote',
    85000, 
    125000,
    'USD',
    true,
    'full-time',
    ARRAY['Figma', 'HTML', 'CSS', 'JavaScript', 'React', 'Design Systems'],
    'mid',
    'https://example.com/jobs/ui-ux',
    NOW(),
    true
  ),
  (
    'Data Engineer',
    'DataCorp',
    'Build data pipelines and infrastructure. Work with large-scale data processing using modern tools. Experience with Spark and Airflow preferred.',
    'Boston, MA',
    115000, 
    170000,
    'USD',
    false,
    'full-time',
    ARRAY['Python', 'Spark', 'Airflow', 'SQL', 'AWS', 'ETL'],
    'senior',
    'https://example.com/jobs/data-eng',
    NOW(),
    true
  ),
  (
    'Contract Frontend Developer',
    'ConsultingFirm',
    '6-month contract position for an experienced frontend developer. Work on client projects with flexible hours. Potential for extension or full-time.',
    'Remote',
    80000, 
    100000,
    'USD',
    true,
    'contract',
    ARRAY['React', 'TypeScript', 'Next.js', 'TailwindCSS'],
    'senior',
    'https://example.com/jobs/contract-frontend',
    NOW(),
    true
  );

-- Verify insertion
SELECT COUNT(*) as total_jobs FROM jobs WHERE is_active = true;
